<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1722.45" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.117" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomTabControl\CustomTabControl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="subcontents\EquipmentList\PumpCal.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_HP.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_ceZone.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_Pump.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_ConstructionRoof.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_ConstructionFloor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_Zone.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_Floor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_ConstructionWall.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_HeatingSystem.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\Model.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\sub3dSpaceInfo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\sub3dWallInfo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\sub3dWinInfo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\sub3dBridgeInfo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Construction\ConstructionrRoof.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Construction\ConstructionWall.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="subcontents\ConstructionCW\CW_ImportSize.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ConstructionRoof\Roof_TB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ConstructionFloor\Floor_TB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ConstructionWall\Wall_TB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_Boiler.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_Zone.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\MaterialDB.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>