<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>0.Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'" />

  <ItemGroup>
    <Compile Remove="subcontents\ProjectList\**" />
    <EmbeddedResource Remove="subcontents\ProjectList\**" />
    <None Remove="subcontents\ProjectList\**" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="Microsoft.Office.Interop.Excel">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>9</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>00020813-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="Microsoft.Office.Core">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>8</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>2df8d04c-5bfa-101b-bde5-00aa0044de52</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="0.Logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1722.45" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.117" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.117" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomTabControl\CustomTabControl.csproj" />
    <ProjectReference Include="..\SecureSQLite\wrap_sqlite\wrap_sqlite.vcxproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="contentslist\List_ConstructionBlind.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_ConstructionDoor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_DHWSystem.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_FuelCell.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_AHUSystem.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_SolarTherm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_WindPower.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_PV.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_RESystem.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Alt\AltMain.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Building\ProjectCopy.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Building_Report\Report_Gas.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Element_Report\Element_Chiler.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Element_Report\Element_RESystem.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Element_Report\Element_Win.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Element_Report\Element_ElecHP.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Element_Report\Element_GasHP.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Element_Report\Element_Lighting.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Element_Report\Element_Structure.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Element_Report\Element_Boiler.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\RESystem\SolarTherm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\Alt\AltFloor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\Alt\AltWin.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\Alt\AltRoof.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\Alt\AltWall.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\BuildingGeneral\BlowDoorTest.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\EquipmentList\PumpPower.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\EquipmentList\PumpVolume.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\EquipmentList\ZoneResult.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_AHU.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ZoneGeneral\PreZone.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ThermalBridge\TB_property.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ThermalBridge\TB_List.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Building\OpenProject.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Building\ProjectList.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Building\Intro.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Building_Report\Building_Report.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Building_Report\Report_Elec.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Algorithm_Report\Algorithm_Cooling.cs" />
    <Compile Update="contents\Result\Algorithm_Report\Algorithm_DHW.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Algorithm_Report\Algorithm_AHU.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Algorithm_Report\Algorithm_Lighting.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Result\Algorithm_Report\Algorithm_EnergyNeed.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\System\DHWSystem.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\System\AHUSystem.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ConstructionBlind\BlindDB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ThermalBridge\TB_DB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\DHWSystem\DHW_PumpDB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\GWHP_DB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\GroundHP_DB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\EquipmentList\PumpCal.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\DHWSystem\DHWDH_DB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\DHWSystem\DHW_BoilerDB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\DHWSystem\DHW_SolarDB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\DHWSystem\DHW_Zone.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\DH_DB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ABS_DB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_Solar.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\AirHP_DB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_ceZone.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_Pump.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_ConstructionRoof.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_ConstructionFloor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_Zone.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_Floor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_ConstructionWall.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contentslist\List_HeatingSystem.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\Model.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\sub3dSpaceInfo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\sub3dWallInfo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\sub3dWinInfo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\3D\sub3dBridgeInfo.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Construction\ConstructionrRoof.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="contents\Construction\ConstructionWall.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="subcontents\ConstructionCW\CW_ImportSize.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ConstructionRoof\Roof_TB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ConstructionFloor\Floor_TB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\ConstructionWall\Wall_TB.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_Boiler.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\HeatingSystem\Heating_Zone.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="subcontents\MaterialDB.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>